WELCOME_GREET = [

"Welcome to our <b>Disease Prediction and Hospital Recommendation Chatbot!</b> I'm here to help you understand potential diseases based on your symptoms, and recommend the best hospitals and clinics in your area. Let's get started by gathering some information about your symptoms. For reference to test and predict the dummyb disease use the symptoms as follows: itching, skin rash, nodal skin eruptions, dischromic patches. For more symptoms to test our chatbot please <a href='https://github.com/JayaSanjay2003/healthbot-ml/blob/master/symptoms_refernce.xlsx'>click here</a>.",
        "Hello there! Welcome to our <b>Disease Prediction and Hospital Recommendation Chatbot!</b> I'm here to help you find out what might be causing your symptoms, and suggest the best hospitals and clinics for you to visit. To get started, please tell me about the symptoms you're experiencing.",
        "Thank you for choosing our <b>Disease Prediction and Hospital Recommendation Chatbot!</b> I'm here to assist you in identifying possible health conditions based on your symptoms, and provide you with hospital recommendations in your area. Let's begin by learning more about your symptoms.",
        "Greetings! Welcome to our <b>Disease Prediction and Hospital Recommendation Chatbot!</b> I'm here to help you determine the possible diseases you could be suffering from based on your symptoms, and suggest the most suitable hospitals and clinics for you. To get started, please describe the symptoms you're experiencing.",
        "Welcome to our <b>Disease Prediction and Hospital Recommendation Chatbot!</b> I'm here to help you identify the health conditions you might have based on your symptoms, and recommend the best hospitals and clinics near you. To begin, please share some information about your symptoms."
    ]

